language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
script:
- npm test
- test $TRAVIS_PULL_REQUEST != 'false' || npm run test-browser
after_script:
- npm run coveralls
env:
  global:
  - secure: Ss/fW8UieXKKIS9oMeStUi9cq5+SNS8rjw+I1Kps/IV/fC36rNkGbe5bEV6GIPzRfrvJ+Y2R1sZyGsgzyaLt1JBU8Z6e+CT3PMivmE0FumCMDt8vs1DVuHn7KUlWkviS7JwQ0GzI4shwiZkZ6O4znQF5l6ncOzoWBxF/oj9LdOw=
  - secure: B/JOeVavxK+cEK3ezAzCzSfkIUvJly5m5KipuAvbhRJjNwyB44macJBBSGZEVY+DzMq6ZGn5fTJVz0t+vQh+4SRFBzoJCsmZfRd/1sQEc0UTQQHxd7AGTQW4MJP7rhEL9OI5Nx4YYV9z3bPAXQnSlvcUHxXNSSddUk2P4d3rUjw=
addons:
  sauce_connect: true
